from typing import Protocol


class JobCrawler(Protocol):
    def fetch(self) -> list[dict]: ...


class JobRepository(Protocol):
    def load(self) -> dict: ...
    def save(self, pool: dict) -> None: ...
    def update(self, pool: dict, jobs: list[dict], today: str) -> dict: ...
    def flush_closed(self, pool: dict) -> dict: ...
    def candidates(self, pool: dict, mode: str, today: str) -> list[dict]: ...
    def summary(self, pool: dict) -> dict: ...


class SnapshotStore(Protocol):
    def cleanup(self, retain_days: int) -> None: ...
    def fetch_batch(self, jobs: list[dict], today: str) -> dict[str, str]: ...


class Ranker(Protocol):
    def rank(self, jobs: list[dict], top_n: int) -> tuple[list[dict], list[dict]]: ...


class Notifier(Protocol):
    def notify_recommendations(
        self,
        top_jobs: list[dict],
        rest_jobs: list[dict],
        snapshots: dict[str, str],
        mode_label: str,
    ) -> None: ...
